name = input('what is your name?:')
print('hello', name, 'welcome to your shoelace tutorial')
print('step 1: fold each end of the lace into a single bunny ear')
ready = input('type ready if you finished step 1, if you havent finished, try again')
print('okay now that you are', ready, 'its time for step 2')
print('step 2: now you want to cross the bunny ears so that they make an x shape in the air')
ready2 = input('type ready if you finished step 2, if you havent finished, try again')
print('okay since you are', ready2, 'its time for step 3')
print('step 3: loop the bottom bunny ear over and through the top bunny ear')
ready3 = input('type ready if you finished step 3, if you havent finished, try again')
print('okay since you are', ready3, 'its time for step 4')
print('okay now you are ready for the final step')
print('step 4: pull the bunny ears out to the side away from the shoe')
finished = input('type finished if youre shoelaces are tied, if they arent, restart the tutorial')
print('congratulations, you are', finished,)
